### ISSUE TITLE
Crear plugin theme geonode basado en definiciones de datosgobar/portal-geoandino/issues/2

### ISSUE THREAD

**Issue by lalo73** [datosgobar/portal-geoandino#13]
Permitir:
- [x] Titulo del portal
- [x] Descripcion
- [x] Imagen de fondo
- Formato de los temas:
  - [x] Temas con íconos: Mostrar temas con íconos y descripción
  - [x] Temas sin íconos: Mostrar temas solo con descripción
- [x] Logo en el encabezado
- Redes sociales y contacto
  - [x] Facebook
  - [x] Twitter
  - [x] Github
  - [x] Mail de contacto
- [x] Logo de pie de pagina
- [x] URL del logo de pie de pagina
- [x] Description de los Datases
- Organizaciones con datos (opcional)
  - [x] Queres que esta seccion se vea en tu portal?
- Acerca (opcional)
  - [x] Queres que esta seccion se vea en tu portal?
  - [x] Titulo
  - [x] Description
- Metadatos (Facebook  & Google)
  - [x] Titulo de tu portal
  - [x] Descripcion
  - [x] Imagen de portada

**Comment by poligarcia** [comment]
datosgobar/portal-geoandino/issues/2
