### ISSUE TITLE
Tareas de pre-release Geoandino

### ISSUE THREAD

**Issue by lalo73** [datosgobar/portal-geoandino#23]
## Cambios menores
- [x] Ansible muestra el siguiente warning:
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is
 discouraged. The module documentation details page may explain more about this
 rationale.. This feature will be removed in a future release. Deprecation

- [x] Nuestra imagen de postgres esta basada en  mdillon/postgis:9.6 debido a un probleman con debian y la instalacion de docker. El problema ya se soluciono, ya se puede volver a usar la imagen oficial de postgres:9.6

- [x] Actualizar .travis.yml para que instale compose 1.16 en vez de 1.13

- [x] Verificar que use la ultima version del theme

## Antes de lazar la version estable:

- [x] Hacer un tag nuevo
- [x] Borrar todos los tag excepto el ultimo

- [x] Asegurarse que todos las referencias en latest.yml hagan referencia a la ultima imagen creadad por el ultimo tag en github.
- [x] Asegurarse que geoandino geonetwork, geoserver, psql apunten a esa ultima version.
- [x] Borrar imagenes antiguas, dejando solo :latest y el ultimo tag

**Comment by poligarcia** [comment]
Cual es el módulo que tira el `DEPRECATION WARNING` y con qué lo reemplazamos?

**Comment by lalo73** [comment]
No es un modulo, es el keyword ` include`, que usamos para incluir tareas de otros archivos.
Por ejemplo aca: https://github.com/datosgobar/portal-geoandino/blob/master/geonode/roles/geoandino/tasks/main.yml

Ahi deberiamos usar `import_task`, creo.
